# Site
title: Raja Hasnain Anwar
description: Data Science Enthusiast
url: https://rhasnainanwar.github.io/
logo: hasnain.jpg                            # Site logo
locale: en_US

# Left Block Images
background:
  homepage: images/home.jpg                           # this image will be shown on homepage's left block
  post-list: images/posts.jpg             # this image will be shown on post list page
  default-post: images/default.jpg   # this image will be shown when post's front matter doesn't specify any image

# Jekyll
permalink:          /:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
sass:
  sass_dir:         assets/_sass
  style:            compressed

# Google Analytics
#google-analytics: UA-XXXXX-Y

# Social Links
email: rajahasnain570@gmail.com
#google.plus:        username
twitter: RHasnainAnwar
facebook: raja.hasnain.570
github: rhasnainanwar
linkedin: rajahasnain570
quora: Raja-Hasnain-Anwar
#instagram:          username
#lastfm:            username
#tumblr:            username
#pinterest:         username
#foursquare:        username
#steam:              username
#dribbble:          username
#youtube:           username
#soundcloud:        username
#weibo:             username
#flickr:            username
#codepen:           username
#keybase:           username
#xmpp:              username@server.com
#hackernews:        username

# Gems
gems:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

plugins:
  - jekyll-feed
  - jekyll-seo-tag
# Exclude list
include: [_pages]
exclude: [README.md, Gemfile, Gemfile.lock, _site, src, vendor, CNAME, LICENSE, Rakefile, .sass-cache, .DS_Store]
